# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmoyz8Iquo7LFB9YTdECiciwH0E0YR5Q
"""

import numpy as np
import random
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


def generar_caso_de_uso_evaluar_clustering_kmeans():
    """
    Genera un caso de uso aleatorio para la función:
    evaluar_clustering_kmeans(X, n_clusters)

    Retorna:
        input_data: dict con las entradas de la función
        output_data: tupla esperada
    """

    # -----------------------------
    # 1. Crear entradas aleatorias
    # -----------------------------
    n_samples = random.randint(20, 80)
    n_features = random.randint(2, 4)
    n_clusters = random.randint(2, 4)

    # Asegurar que haya suficientes muestras
    n_samples = max(n_samples, n_clusters + 2)

    X, _ = make_blobs(
        n_samples=n_samples,
        centers=n_clusters,
        n_features=n_features,
        cluster_std=random.uniform(0.5, 1.8),
        random_state=random.randint(0, 10000)
    )

    # -----------------------------
    # 2. Construir input_data
    # -----------------------------
    input_data = {
        "X": X.copy(),
        "n_clusters": n_clusters
    }

    # -----------------------------
    # 3. Calcular output_data
    # -----------------------------
    model = KMeans(n_clusters=n_clusters, random_state=0, n_init=10)
    labels = model.fit_predict(X)
    centroids = model.cluster_centers_
    score = silhouette_score(X, labels)

    output_data = (labels, centroids, score)

    return input_data, output_data


if __name__ == "__main__":
    entrada, salida = generar_caso_de_uso_evaluar_clustering_kmeans()

    print("=== INPUT ===")
    print("Claves:", entrada.keys())
    print("X shape:", entrada["X"].shape)
    print("n_clusters:", entrada["n_clusters"])

    print("\n=== OUTPUT ESPERADO ===")
    print("labels shape:", salida[0].shape)
    print("centroids shape:", salida[1].shape)
    print("score:", salida[2])