# -*- coding: utf-8 -*-
"""question-0002-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLPgDXMH_Et9oXBPxo_C4DZn6UaGQ93U
"""

import pandas as pd
import numpy as np
import random


def generar_caso_de_uso_detectar_cambios_percentuales():
    """
    Genera un caso de uso aleatorio para la función:
    detectar_cambios_percentuales(df, grupo_col, tiempo_col, valor_col, umbral)

    Retorna:
        input_data: dict con las entradas de la función
        output_data: DataFrame esperado
    """

    # -----------------------------
    # 1. Crear entradas aleatorias
    # -----------------------------
    grupo_col = "maquina"
    tiempo_col = "instante"
    valor_col = "temperatura"

    n_grupos = random.randint(2, 5)
    grupos = [f"M{i}" for i in range(1, n_grupos + 1)]

    filas = []

    for grupo in grupos:
        n_mediciones = random.randint(4, 8)
        tiempos = list(range(1, n_mediciones + 1))

        # Valores positivos para evitar problemas con pct_change
        valores = np.round(np.random.uniform(10, 200, size=n_mediciones), 2)

        for t, v in zip(tiempos, valores):
            filas.append({
                grupo_col: grupo,
                tiempo_col: t,
                valor_col: v
            })

    df = pd.DataFrame(filas)

    # Mezclar filas para que el orden inicial no sea trivial
    df = df.sample(frac=1).reset_index(drop=True)

    umbral = round(random.uniform(0.10, 0.60), 2)

    # -----------------------------
    # 2. Construir input_data
    # -----------------------------
    input_data = {
        "df": df.copy(),
        "grupo_col": grupo_col,
        "tiempo_col": tiempo_col,
        "valor_col": valor_col,
        "umbral": umbral
    }

    # -----------------------------
    # 3. Calcular output_data
    # -----------------------------
    df_expected = df.copy()
    df_expected = df_expected.sort_values([grupo_col, tiempo_col]).reset_index(drop=True)

    df_expected["cambio_pct"] = df_expected.groupby(grupo_col)[valor_col].pct_change()

    output_data = (
        df_expected[df_expected["cambio_pct"].notna()]
        .loc[lambda x: x["cambio_pct"].abs() > umbral]
        .reset_index(drop=True)
    )

    return input_data, output_data


if __name__ == "__main__":
    entrada, salida = generar_caso_de_uso_detectar_cambios_percentuales()

    print("=== INPUT ===")
    print("Claves:", entrada.keys())
    print(entrada["df"].head())
    print("Umbral:", entrada["umbral"])

    print("\n=== OUTPUT ESPERADO ===")
    print(salida.head())