# -*- coding: utf-8 -*-
"""question-0003-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDi6ff4CiLLyFR1ymcZGXmVTJhPa1t1e
"""

import numpy as np
import random
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression


def generar_caso_de_uso_entrenar_regresion_escalada():
    """
    Genera un caso de uso aleatorio para la función:
    entrenar_regresion_escalada(X_train, y_train, X_test)

    Retorna:
        input_data: dict con las entradas de la función
        output_data: tupla esperada
    """

    # -----------------------------
    # 1. Crear entradas aleatorias
    # -----------------------------
    n_train = random.randint(20, 60)
    n_test = random.randint(5, 20)
    n_features = random.randint(2, 6)

    # Generar columnas con escalas distintas
    X_train_cols = []
    X_test_cols = []

    for _ in range(n_features):
        escala = random.choice(["small", "medium", "large"])

        if escala == "small":
            train_col = np.random.uniform(0, 1, size=n_train)
            test_col = np.random.uniform(0, 1, size=n_test)
        elif escala == "medium":
            train_col = np.random.uniform(0, 100, size=n_train)
            test_col = np.random.uniform(0, 100, size=n_test)
        else:
            train_col = np.random.uniform(-500, 500, size=n_train)
            test_col = np.random.uniform(-500, 500, size=n_test)

        X_train_cols.append(train_col)
        X_test_cols.append(test_col)

    X_train = np.column_stack(X_train_cols)
    X_test = np.column_stack(X_test_cols)

    # Construir y_train como combinación lineal + ruido
    coeficientes = np.random.uniform(-3, 3, size=n_features)
    ruido = np.random.normal(0, 0.5, size=n_train)
    y_train = X_train @ coeficientes + ruido

    # -----------------------------
    # 2. Construir input_data
    # -----------------------------
    input_data = {
        "X_train": X_train.copy(),
        "y_train": y_train.copy(),
        "X_test": X_test.copy()
    }

    # -----------------------------
    # 3. Calcular output_data
    # -----------------------------
    scaler = StandardScaler()
    X_train_escalado = scaler.fit_transform(X_train)
    X_test_escalado = scaler.transform(X_test)

    model = LinearRegression()
    model.fit(X_train_escalado, y_train)
    y_pred = model.predict(X_test_escalado)

    output_data = (X_train_escalado, X_test_escalado, y_pred)

    return input_data, output_data


if __name__ == "__main__":
    entrada, salida = generar_caso_de_uso_entrenar_regresion_escalada()

    print("=== INPUT ===")
    print("Claves:", entrada.keys())
    print("X_train shape:", entrada["X_train"].shape)
    print("y_train shape:", entrada["y_train"].shape)
    print("X_test shape:", entrada["X_test"].shape)

    print("\n=== OUTPUT ESPERADO ===")
    print("X_train_escalado shape:", salida[0].shape)
    print("X_test_escalado shape:", salida[1].shape)
    print("y_pred shape:", salida[2].shape)