# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnVB-rjRpXuWwgZKRvA7duAcHbK540yw
"""

import pandas as pd
import numpy as np
import random


def generar_caso_de_uso_resumir_ventas_mensuales():
    """
    Genera un caso de uso aleatorio para la función:
    resumir_ventas_mensuales(df, fecha_col, categoria_col, monto_col)

    Retorna:
        input_data: dict con las entradas de la función
        output_data: DataFrame esperado
    """

    # -----------------------------
    # 1. Crear entradas aleatorias
    # -----------------------------
    n_rows = random.randint(10, 40)

    fecha_col = "fecha_venta"
    categoria_col = "categoria"
    monto_col = "monto"

    categorias_posibles = ["ropa", "hogar", "tecnologia", "deportes", "salud"]

    # Fechas aleatorias dentro de varios meses
    fechas = pd.to_datetime(
        np.random.choice(
            pd.date_range("2025-01-01", "2025-06-30", freq="D"),
            size=n_rows
        )
    )

    categorias = np.random.choice(categorias_posibles, size=n_rows)
    montos = np.round(np.random.uniform(5, 500, size=n_rows), 2)

    df = pd.DataFrame({
        fecha_col: fechas,
        categoria_col: categorias,
        monto_col: montos
    })

    # -----------------------------
    # 2. Construir input_data
    # -----------------------------
    input_data = {
        "df": df.copy(),
        "fecha_col": fecha_col,
        "categoria_col": categoria_col,
        "monto_col": monto_col
    }

    # -----------------------------
    # 3. Calcular output_data
    # -----------------------------
    df_expected = df.copy()
    df_expected[fecha_col] = pd.to_datetime(df_expected[fecha_col])
    df_expected["mes"] = df_expected[fecha_col].dt.to_period("M").astype(str)

    output_data = (
        df_expected
        .groupby(["mes", categoria_col])[monto_col]
        .agg(["sum", "mean", "count"])
        .reset_index()
        .rename(columns={
            "sum": "suma_monto",
            "mean": "promedio_monto",
            "count": "cantidad_registros"
        })
        .sort_values(["mes", categoria_col])
        .reset_index(drop=True)
    )

    return input_data, output_data


if __name__ == "__main__":
    entrada, salida = generar_caso_de_uso_resumir_ventas_mensuales()

    print("=== INPUT ===")
    print("Claves:", entrada.keys())
    print(entrada["df"].head())

    print("\n=== OUTPUT ESPERADO ===")
    print(salida.head())